### ISSUE TITLE
On Stream Review

### ISSUE THREAD

**Issue by braddotcoffee** [70sh1/eddy#1]
### Core.go
* Core.go is currently acting as a sort of generic "utils" file
* "PJZ_here: it's like thje junk drawer of your code base" <- general comment about having a "utils" file
* I think this is a super apt metaphor where it can become very difficult to find things that are in this "junk drawer" as the project grows
* It might be nice to think about pulling some of this stuff out into more specific "modules"
* [Great Code Aesthetic video that covers this](https://youtu.be/-J3wNP6u5YU?si=-AIzTI7cbzUnrYEj&t=346)

### Progress Bars
* Your UI is currently fairly coupled to your business logic since the core "Encrypt" and "Decrypt" functionality is "progress-bar-aware". 
* It would be nice to have some sort of "UI" module that encapsulates these progress bars and is communicated to via channels (or something similar) from the Encrypt / Decrypt process
  * Encrypt and decrypt then use these channels to communicate meaningful information about their process that any "subscriber" could theoretically use from a reference to these channels
  * This makes it extensible for if you want other parts of your code to know what's going on in the Encrypt/Decrypt process

**Comment by 70sh1** [comment]
Both points have been addressed:
252d694a57619d546f842dfb6edc04d493a2c84a
55316c4718fcd37f522d1aeb1d1935260de6d19e

Thank you for the review, Brad
